Task 1 version 1
sergey-berezin/401_tokar pull request #1
Opened 2024-09-27 14:13 UTC by Doodox098

2024-10-01 08:06 UTC, sergey-berezin requested changes

2024-10-01 08:06 UTC, sergey-berezin commented on App/Program.cs
> +            Process.GetCurrentProcess().Kill();
Такое завершение процесса здесь лишнее. Kill не рекомендуется использовать без серьезной на то необходимости.

2024-10-01 08:06 UTC, sergey-berezin commented on App/Program.cs
> +            foreach (var city in evolution.Population.Last().RawTable) {
Дублирование кода вывода результата на экран. Лучше сделать один раз после цикла в main.

2024-10-01 12:05 UTC, Doodox098 commented
Исправил обработку сигнала Ctrl+C, нужно ли приходить в следующий раз для досдачи задания?

2024-10-02 13:26 UTC, sergey-berezin commented
> Исправил обработку сигнала Ctrl+C, нужно ли приходить в следующий раз для досдачи задания?

Приходить не нужно. Первое задание принято.

2024-10-02 13:26 UTC, merged